title: Paul Newton-Jackson
email: paul@greenfootprint.co.nz
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Paul Newton-Jackson, scholar, composer and music editor, 
  with information about publications, compositions, and editions of early music.
baseurl: ""
url: "https://paulnewtonjackson.com"

# Build settings
plugins:
  - jekyll-seo-tag

sass:
  style: compressed